spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: springCloud
#     username: root
    password: 123
    url: jdbc:mysql://39.100.132.214:3306/SpringCloud_Shell?characterEncoding=utf-8&useSSL=false
#     url: jdbc:mysql://localhost:3306/springcloud_shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379
