spring:
  redis:
    host: "47.92.249.250"
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: 10000
        min-idle: 2
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: springCloud
    password: 123
    url: jdbc:mysql://39.100.132.214:3306/SpringCloud_Shell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
